name: payments-tests

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
      JWT_SECRET: asdffg
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm i && npm run test:ci
